cabal-version:      3.0
name:               taxi-driver
version:            0.1.0.0
license:            BSD-2-Clause
license-file:       LICENSE
author:             Niek Mulleners
maintainer:         n.mulleners@uu.nl
build-type:         Simple
extra-doc-files:    CHANGELOG.md

common shared-properties
  ghc-options: -Wall

  default-language: GHC2024

  default-extensions:
      BlockArguments
    , DefaultSignatures
    , DerivingVia
    , DuplicateRecordFields
    , NoImplicitPrelude
    , NoFieldSelectors
    , OverloadedStrings
    , OverloadedRecordDot
    , PatternSynonyms
    , ViewPatterns

  build-depends:
      base
    , containers
    , directory
    , lens
    , prettyprinter
    , text

library
  import:           shared-properties

  exposed-modules:
    , Bench
    , Bench.Model
    , Language.Type
    , Language.Expr
    , Language.Container
    , Language.Container.Morphism
    , Language.Container.Relation
    , Language.Coverage
    , Language.Parser
    , Language.Prelude
    , Language.Pretty
    , Language.Arbitrary
    , Language.Problem
    , Language.Relevance
    , Synth
    , Tactic
    , Tactic.Check
    , Tactic.Combinators
    , Tactic.Constructors
    , Tactic.Core
    , Tactic.Elim
    , Tactic.Extract
    , Tactic.Filter
    , Tactic.Fold
    , Tactic.Hole
    , Tactic.Ignore
    , Tactic.Map
    , Tactic.Predicate
    , Tactic.Relation
    , Tactic.Settings
    , Tactic.Tango
    , Test

  build-depends:
      fused-effects
    , megaparsec
    , monad-dijkstra
    , taxi-driver-prelude
    , QuickCheck

  hs-source-dirs:   src

library taxi-driver-prelude
  import:           shared-properties

  exposed-modules:
      Base
    , Control.Effect.Fresh.Named
    , Control.Effect.Search
    , Control.Effect.Weight
    , Data.Map.Multi
    , Data.Map.Utils
    , Data.Name
    , Data.Nat
    , Data.Tango.List.List
    , Data.Tango.List.Nat
    , Data.Tree.Binary
    , Utils

  build-depends:
      fused-effects
    , monad-dijkstra
    , QuickCheck
    , random

  hs-source-dirs:   prelude

test-suite taxi-driver-test
  import:           shared-properties

  type:             exitcode-stdio-1.0

  hs-source-dirs:   test

  main-is:          Main.hs

  build-depends:
      fused-effects
    , taxi-driver
    , taxi-driver-prelude
    , QuickCheck
    , tasty
    , tasty-quickcheck
    , tasty-hunit

benchmark taxi-driver-bench
  import:           shared-properties

  type:             exitcode-stdio-1.0

  hs-source-dirs:   bench

  main-is:          Main.hs

  build-depends:
      optparse-applicative
    , taxi-driver
    , taxi-driver-prelude
    , QuickCheck
    , tasty
    , tasty-bench
